// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: seankhliao/archrepo/v1alpha1/archrepo.proto

package archrepo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePackageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePackageRequest) Reset() {
	*x = CreatePackageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageRequest) ProtoMessage() {}

func (x *CreatePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageRequest.ProtoReflect.Descriptor instead.
func (*CreatePackageRequest) Descriptor() ([]byte, []int) {
	return file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescGZIP(), []int{0}
}

type CreatePackageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePackageResponse) Reset() {
	*x = CreatePackageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePackageResponse) ProtoMessage() {}

func (x *CreatePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePackageResponse.ProtoReflect.Descriptor instead.
func (*CreatePackageResponse) Descriptor() ([]byte, []int) {
	return file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescGZIP(), []int{1}
}

var File_seankhliao_archrepo_v1alpha1_archrepo_proto protoreflect.FileDescriptor

var file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x65, 0x61, 0x6e, 0x6b, 0x68, 0x6c, 0x69, 0x61, 0x6f, 0x2f, 0x61, 0x72, 0x63,
	0x68, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x61,
	0x72, 0x63, 0x68, 0x72, 0x65, 0x70, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61,
	0x72, 0x63, 0x68, 0x72, 0x65, 0x70, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x5f, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x72,
	0x65, 0x70, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x72,
	0x65, 0x70, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x6f, 0x2e,
	0x73, 0x65, 0x61, 0x6e, 0x6b, 0x68, 0x6c, 0x69, 0x61, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x61, 0x72, 0x63, 0x68, 0x72, 0x65, 0x70, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescOnce sync.Once
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescData = file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDesc
)

func file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescGZIP() []byte {
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescOnce.Do(func() {
		file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescData = protoimpl.X.CompressGZIP(file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescData)
	})
	return file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDescData
}

var file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seankhliao_archrepo_v1alpha1_archrepo_proto_goTypes = []interface{}{
	(*CreatePackageRequest)(nil),  // 0: archrepo.CreatePackageRequest
	(*CreatePackageResponse)(nil), // 1: archrepo.CreatePackageResponse
}
var file_seankhliao_archrepo_v1alpha1_archrepo_proto_depIdxs = []int32{
	0, // 0: archrepo.RepoService.CreatePackage:input_type -> archrepo.CreatePackageRequest
	1, // 1: archrepo.RepoService.CreatePackage:output_type -> archrepo.CreatePackageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seankhliao_archrepo_v1alpha1_archrepo_proto_init() }
func file_seankhliao_archrepo_v1alpha1_archrepo_proto_init() {
	if File_seankhliao_archrepo_v1alpha1_archrepo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePackageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seankhliao_archrepo_v1alpha1_archrepo_proto_goTypes,
		DependencyIndexes: file_seankhliao_archrepo_v1alpha1_archrepo_proto_depIdxs,
		MessageInfos:      file_seankhliao_archrepo_v1alpha1_archrepo_proto_msgTypes,
	}.Build()
	File_seankhliao_archrepo_v1alpha1_archrepo_proto = out.File
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_rawDesc = nil
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_goTypes = nil
	file_seankhliao_archrepo_v1alpha1_archrepo_proto_depIdxs = nil
}
